export const appVersion = "۰.۹";
// export const apiUrl = "http://10.25.245.51:3000/api/v1";
export const apiUrl = "http://localhost:3000/api/v1";
export const militaryBaseName = "Shahid_Khazraii";

export const roles = {
  can_do_all: {
    label: "ادمین",
    badgeColor: "primary",
  },
  operator: {
    label: "متصدی آمار",
    badgeColor: "teal",
  },
  admin_head: {
    label: "رئیس اداری",
    badgeColor: "blue",
  },
  admin_succ: {
    label: "جانشین اداری",
    badgeColor: "blue-4",
  },
  head: {
    label: "فرمانده",
    badgeColor: "pink",
  },
  succ: {
    label: "جانشین",
    badgeColor: "pink-4",
  },
};

export const statuses = {
  Hazer: "حاضر",
  Negahban: "نگهبان",
  EsterahatNegahbani: "استراحت نگهبانی",
  EsterahatTirandazi: "استراحت تیراندازی",
  EsterahatShift: "استراحت شیفت",
  MamoorDoor: "مامور دور",
  MamoorNazdik: "مامور نزدیک",
  TasvieHesab: "تسویه حساب",
  ModavematKar: "مداومت کار",
  EsterahatPezeshki: "استراحت پزشکی",
  Morkhasi: "مرخصی",
  Ghayeb: "غایب",
  Farari: "فراری",
  BazdashtGaah: "بازداشتگاه",
  TirandaziRoozane: "تیراندازی روزانه",
  Montaseb: "منتسب",
  RahDoor: "راه دور",
  Bimarestan: "بیمارستان",
};

export const ranks = {
  "000": "نامشخص",
  100: "محصل پيماني",
  101: "هنراموزگروهباني‌",
  201: "اموزشيار",
  202: "م--رب-ي ",
  203: "استادي-ار",
  204: "دانش-يار",
  205: "اس-تاد",
  210: "سرهمافريكم ",
  211: "سرهمافردوم ",
  212: "سرهمافرسوم ",
  213: "همافريكم ",
  214: "همافردوم ",
  215: "همافرسوم ",
  225: "دانشجوي سال  1 پرستاري ",
  226: "دانشجوي سال  2 پرستاري ",
  227: "دانشجوي سال  3 پرستاري ",
  228: "هنراموزگروهباني ",
  236: "دانشجوي سال  1 نظامي ",
  237: "دانشجوي سال  2 نظامي ",
  238: "دانشجوي سال  3 نظامي ",
  239: "دانشجوي سال  4 نظامي ",
  243: "محصل  پيماني ",
  244: "دانشاموزبهياري ",
  311: "ستوانياريكم ",
  312: "ستوانياردوم ",
  313: "ستوانيارسوم ",
  381: "ك  ت  ر 1",
  382: "ك  ت  ر 2",
  383: "ك  ت  ر 3",
  384: "ك  ت  ر 4",
  385: "ك  ت  ر 5",
  386: "ك  ت  ر 6",
  387: "ك  ت  ر 7",
  388: "ك  ت  ر 8",
  389: "ك  ت  ر 9",
  390: "ك  ت  ر 10",
  391: "ك  ت  ر 11",
  392: "ك  ت  ر 12",
  393: "ك  ت  ر 13",
  394: "ك  ت  ر 14",
  395: "ك  ت  ر 15",
  396: "ك  ت  ر 16",
  397: "ك  ت  ر 17",
  398: "ك  ت  ر 18",
  399: "ك  ت  ر 19",
  400: "ك  ت  ر 20",
  401: "ك  ع  ر 1",
  402: "ك  ع  ر 2",
  403: "ك  ع  ر 3",
  404: "ك  ع  ر 4",
  405: "ك  ع  ر 5",
  406: "ك  ع  ر 6",
  407: "ك  ع  ر 7",
  408: "ك  ع  ر 8",
  409: "ك  ع  ر 9",
  410: "ك  ع  ر 10",
  411: "ك  ع  ر 11",
  412: "ك  ع  ر 12",
  413: "ك  ع  ر 13",
  414: "ك  ع  ر 14",
  415: "ك  ع  ر 15",
  416: "ك  ع  ر 16",
  417: "ك  ع  ر 17",
  418: "ك  ع  ر 18",
  419: "ك  ع  ر 19",
  420: "ك  ع  ر 20",
  421: "افزارمندازمايشي ",
  424: "افزارمندطبقه 1",
  430: "افزارمندطبقه 2",
  436: "افزارمندطبقه 3",
  442: "افزارمندطبقه 4",
  448: "افزارمندطبقه 5",
  457: "كارمندفني ط 1پايه 1",
  458: "كارمندفني ط 1پايه 2",
  459: "كارمندفني ط 1پايه 3",
  460: "كارمندفني ط 1پايه 4",
  461: "كارمندفني ط 1پايه 5",
  462: "كارمندفني ط 1پايه 6",
  463: "كارمندفني ط 1پايه 7",
  464: "كارمندفني ط 1پايه 8",
  465: "كارمندفني ط 1پايه 9",
  466: "كارمندفني ط 1پايه 10",
  472: "كارمندفني ط 2پايه 1",
  473: "كارمندفني ط 2پايه 2",
  474: "كارمندفني ط 2پايه 3",
  475: "كارمندفني ط 2پايه 4",
  476: "كارمندفني ط 2پايه 5",
  477: "كارمندفني ط 2پايه 6",
  478: "كارمندفني ط 2پايه 7",
  479: "كارمندفني ط 2پايه 8",
  480: "كارمندفني ط 2پايه 9",
  481: "كارمندفني ط 2پايه 10",
  487: "كارمندفني ط 3پايه 1",
  488: "كارمندفني ط 3پايه 2",
  489: "كارمندفني ط 3پايه 3",
  490: "كارمندفني ط 3پايه 4",
  491: "كارمندفني ط 3پايه 5",
  492: "كارمندفني ط 3پايه 6",
  493: "كارمندفني ط 3پايه 7",
  494: "كارمندفني ط 3پايه 8",
  495: "كارمندفني ط 3پايه 9",
  496: "كارمندفني ط 3پايه 10",
  502: "كارمندفني ط 4پايه 1",
  503: "كارمندفني ط 4پايه 2",
  504: "كارمندفني ط 4پايه 3",
  505: "كارمندفني ط 4پايه 4",
  506: "كارمندفني ط 4پايه 5",
  507: "كارمندفني ط 4پايه 6",
  508: "كارمندفني ط 4پايه 7",
  509: "كارمندفني ط 4پايه 8",
  510: "كارمندفني ط 4پايه 9",
  511: "كارمندفني ط 4پايه 10",
  517: "كارمندفني ط 5پايه 1",
  518: "كارمندفني ط 5پايه 2",
  519: "كارمندفني ط 5پايه 3",
  520: "كارمندفني ط 5پايه 4",
  521: "كارمندفني ط 5پايه 5",
  522: "كارمندفني ط 5پايه 6",
  523: "كارمندفني ط 5پايه 7",
  524: "كارمندفني ط 5پايه 8",
  525: "كارمندفني ط 5پايه 9",
  526: "كارمندفني ط 5پايه 10",
  541: "كارمندرسمي ط 1 مرتبه 1",
  556: "كارمندرسمي ط 1 مرتبه 2",
  571: "كارمندرسمي ط 1 مرتبه 3",
  586: "كارمندرسمي ط 1 مرتبه 4",
  611: "كارمندرسمي ط 2 مرتبه  1",
  612: "كارمندرسمي ط 2 مرتبه  2",
  613: "كارمندرسمي ط 2 مرتبه  3",
  614: "كارمندرسمي ط 2 مرتبه  4",
  615: "كارمندرسمي ط 3 مرتبه  1",
  616: "كارمندرسمي ط 3 مرتبه  2",
  617: "كارمندرسمي ط 3 مرتبه  3",
  618: "كارمندرسمي ط 3 مرتبه  4",
  706: "گ 2 پيماني ",
  707: "گ 1 پيماني ",
  708: "استوار2 پيماني ",
  709: "استوار1 پيماني ",
  710: "ستوان 3 پيماني ",
  711: "ستوان 2 پيماني ",
  712: "ستوان 1 پيماني ",
  713: "سروان   پيماني ",
  722: "ك  پ  ر 2",
  723: "ك  پ  ر 3",
  724: "ك  پ  ر 4",
  725: "ك  پ  ر 5",
  726: "ك  پ  ر 6",
  727: "ك  پ  ر 7",
  728: "ك  پ  ر 8",
  729: "ك  پ  ر 9",
  730: "ك  پ  ر 10",
  731: "ك  پ  ر 11",
  732: "ك  پ  ر 12",
  733: "ك  پ  ر 13",
  734: "ك  پ  ر 14",
  791: "ستوانيكم وظيفه ",
  792: "ستواندوم وظيفه ",
  793: "ستوانسوم وظيفه ",
  794: "گروهبان  سوم وظيفه ",
  795: "گروهبان  دوم وظيفه ",
  796: "گروهبان  يكم وظيفه ",
  797: "استواردوم وظيفه ",
  798: "استواريكم وظيفه ",
  799: "دانشجووظيفه ",
  800: "سربازاموزشي ",
  801: "سرباز",
  802: "سربازدوم ",
  803: "سربازيكم ",
  804: "سرجوخه ",
  805: "گروهبانسوم ",
  806: "گروهباندوم ",
  807: "گروهبانيكم ",
  808: "استواردوم ",
  809: "استواريكم ",
  810: "ستوانسوم ",
  811: "ستواندوم ",
  812: "ستوانيكم ",
  813: "سروان ",
  814: "سرگرد",
  815: "سرهنگ  دوم ",
  816: "سرهنگ ",
  817: "سرتيپ دوم ",
  818: "سرتيپ ",
  819: "سرلشكر",
  820: "سپهبد",
  821: "ارتشبد",
  822: "گروهبان ",
  823: "استوار",
  824: "ستوان ",
};

export const maddeHa = {
  1: { name: "تشویقات", number: 1, table: "Tashvighat" },
  2: { name: "ترفیعات", number: 2, table: "Tarfiat" },
  3: { name: "انتصابات", number: 3, table: "Entesabat" },
  4: { name: "انتقالات", number: 4, table: "Enteghalat" },
  6: { name: "آموزش", number: 6, table: "Amoozesh" },
  7: { name: "وضعیت خدمتی", number: 7, table: "VaziatKhedmat" },
  9: { name: "مسکن", number: 9, table: "Khadamat" },
  10: { name: "استخدام", number: 10, table: "Estekhdam" },
  11: { name: "عائله", number: 11, table: "DastoorAele" },
  12: { name: "تنبیهات", number: 12, table: "Tanbihat" },
  15: { name: "امور متفرقه", number: 15, table: "Motefareghe" },
};

export const maddeHaCols = {
  1: [
    "id",
    "Dastoor",
    "Madde",
    "Zirmadde",
    "ZirZirmadde",
    "Eghdamgar",
    "Girande1",
    "Girande2",
    "Girande3",
    "Girande4",
    "DastoorPeyravi",
    "SahebDastoorPeyravi",
    "DastoorPeyraviCheck",
    "DastoorPeyraviReport",
    "PerNo",
    "TarikhSabt",
    "Madrak",
    "TozihatTakmiliCheck",
    "TozihatTakmili",
    "GirandeCheck",
    "Girande2Check",
    "Girande3Check",
    "Girande4Check",
    "ToReport",
    "TozihatGozareshDastoor",
    "Tarikh",
    "EllateTashvigh",
    "EstenadTashvigh",
    "CodeTashvigh",
    "NahveTashvigh",
    "MadrakTahsili",
    "EstenadArshadiat",
    "SanavatArshadiat",
    "TarikhArshadiat",
    "Date",
    "Girande5",
    "Girande6",
    "Girande7",
    "Girande8",
    "Girande5Check",
    "Girande6Check",
    "Girande7Check",
    "Girande8Check",
    "TaidEghdamgar",
    "TaidRaisShobe",
    "TaidJaneshin",
    "TaidRais",
    "TaidRaisDastoor",
    "TarikhTaidRiasat",
    "TarikhTaidDastoor",
    "TarikhTaidRaisShobe",
    "RaisShobe",
    "Janeshin",
    "Rais",
    "RaisDastoor",
    "OnvanShobe",
    "EmzaEghdamgar",
    "EmzaRaisShobe",
    "EmzaJaneshin",
    "EmzaRais",
    "EmzaRaisDastoor",
    "GirandeLafz",
    "AzTaraf",
    "NamoNeshan",
    "TaidJRaisShobe",
    "JRaisShobe",
    "TarikhTaidJRaisShobe",
    "EmzaJRaisShobe",
    "TarikhOdat",
    "EllateOdat",
    "OdatDahande",
    "DastoorTashvigh",
    "Zamaem",
    "Shobe",
    "RafeTanbihat1",
    "RafeTanbihat2",
    "RafeTanbihat3",
    "Modat",
  ],
  2: [
    "id",
    "Dastoor",
    "Madde",
    "Zirmadde",
    "ZirZirmadde",
    "Eghdamgar",
    "Girande1",
    "Girande2",
    "Girande3",
    "Girande4",
    "Girande5",
    "Girande6",
    "Girande7",
    "Girande8",
    "DastoorPeyravi",
    "MaddePeyravi",
    "SahebDastoorPeyravi",
    "DastoorPeyraviCheck",
    "DastoorPeyraviReport",
    "PerNo",
    "TarikhSabt",
    "Madrak",
    "TozihatTakmiliCheck",
    "TozihatTakmili",
    "GirandeCheck",
    "Girande2Check",
    "Girande3Check",
    "Girande4Check",
    "Girande5Check",
    "Girande6Check",
    "Girande7Check",
    "Girande8Check",
    "ToReport",
    "TozihatGozareshDastoor",
    "Date",
    "TaidEghdamgar",
    "TaidRaisShobe",
    "TaidJaneshin",
    "TaidRais",
    "TaidRaisDastoor",
    "EslahElat",
    "EslahTarikh",
    "ErteghaTarikh",
    "ErteghaMadde",
    "SeyrTedad",
    "GirandeLafz",
    "TarikhTaidRiasat",
    "TarikhTaidDastoor",
    "TarikhTaidRaisShobe",
    "RaisShobe",
    "Janeshin",
    "Rais",
    "RaisDastoor",
    "OnvanShobe",
    "EmzaEghdamgar",
    "EmzaRaisShobe",
    "EmzaJaneshin",
    "EmzaRais",
    "EmzaRaisDastoor",
    "AzTaraf",
    "NamoNeshan",
    "TarikhOdat",
    "EllateOdat",
    "OdatDahande",
    "Zamaem",
    "TakhasosFeli",
    "TakhasosJadid",
    "VaziatFeliGorooh",
    "VaziatFeliRade",
    "VaziatPishnahadiGorooh",
    "VaziatPishnahadiRade",
    "Shobe",
  ],
  3: [
    "id",
    "Dastoor",
    "Madde",
    "Zirmadde",
    "ZirZirmadde",
    "Eghdamgar",
    "Girande1",
    "Girande2",
    "Girande3",
    "Girande4",
    "Girande5",
    "Girande6",
    "Girande7",
    "Girande8",
    "DastoorPeyravi",
    "SahebDastoorPeyravi",
    "DastoorPeyraviCheck",
    "DastoorPeyraviReport",
    "PerNo",
    "TarikhSabt",
    "Madrak",
    "TozihatTakmiliCheck",
    "TozihatTakmili",
    "GirandeCheck",
    "Girande2Check",
    "Girande3Check",
    "Girande4Check",
    "Girande5Check",
    "Girande6Check",
    "Girande7Check",
    "Girande8Check",
    "ToReport",
    "TozihatGozareshDastoor",
    "Date",
    "TarikhEntesab",
    "TaidEghdamgar",
    "TaidRaisShobe",
    "TaidJaneshin",
    "TaidRais",
    "TaidRaisDastoor",
    "GirandeLafz",
    "TarikhTaidRiasat",
    "TarikhTaidDastoor",
    "TarikhTaidRaisShobe",
    "RaisShobe",
    "Janeshin",
    "Rais",
    "RaisDastoor",
    "OnvanShobe",
    "EmzaEghdamgar",
    "EmzaRaisShobe",
    "EmzaJaneshin",
    "EmzaRais",
    "EmzaRaisDastoor",
    "AzTaraf",
    "NamoNeshan",
    "TarikhOdat",
    "EllateOdat",
    "OdatDahande",
    "Zamaem",
    "Semat",
    "MahalSazmani",
    "TakhasosNo",
    "EntesabatTozihat",
    "Serial",
    "Baand",
    "Satr",
    "CodeMadde",
    "m1",
    "m2",
    "m3",
    "m4",
    "m5",
    "SakhtiKar",
    "CodeMaghamat",
    "CodeRahbordi",
    "FogholadeKarshenasi",
    "YeganHoghooghi",
    "SerialAja",
    "NamGhabli",
    "NeshanGhabli",
    "DarajeGhabli",
    "PerNoGhabli",
    "EllatGhabli",
    "TozihatGhabli",
    "Shobe",
  ],
  4: [
    "id",
    "Dastoor",
    "Madde",
    "Zirmadde",
    "ZirZirmadde",
    "Eghdamgar",
    "Girande1",
    "Girande2",
    "Girande3",
    "Girande4",
    "Girande5",
    "Girande6",
    "Girande7",
    "Girande8",
    "DastoorPeyravi",
    "MaddePeyravi",
    "SahebDastoorPeyravi",
    "DastoorPeyraviCheck",
    "DastoorPeyraviReport",
    "PerNo",
    "TarikhSabt",
    "Madrak",
    "TozihatTakmiliCheck",
    "TozihatTakmili",
    "GirandeCheck",
    "Girande2Check",
    "Girande3Check",
    "Girande4Check",
    "Girande5Check",
    "Girande6Check",
    "Girande7Check",
    "Girande8Check",
    "ToReport",
    "TozihatGozareshDastoor",
    "Date",
    "TaidEghdamgar",
    "TaidRaisShobe",
    "TaidJaneshin",
    "TaidRais",
    "TaidRaisDastoor",
    "NamPedar",
    "EnteghalTarikhEnteghal",
    "EnteghalMabda",
    "EnteghalMaghsad",
    "EnteghalBedunHazineCheck",
    "EnteghalMoteahelCheck",
    "EnteghalHamsarCheck",
    "EnteghalFarzandCheck",
    "EnteghalTedadFarzand",
    "EnteghalPedarCheck",
    "EnteghalMadarCheck",
    "EntesabTarikhEntesab",
    "EntesabEstenadie",
    "EntesabDore",
    "EntesabMontasabBe",
    "KhorujTarikhEntesab",
    "KhorujEstenadie",
    "KhorujDore",
    "KhorujMontasabBe",
    "KhorujTarikhKhoruj",
    "TaghirTarikhTaghir",
    "TaghirCodeGhadim",
    "TaghirCodeJadid",
    "KanLamTarikhEnteghal",
    "KanLamPaygah",
    "GirandeLafz",
    "TarikhTaidRiasat",
    "TarikhTaidDastoor",
    "TarikhTaidRaisShobe",
    "RaisShobe",
    "Janeshin",
    "Rais",
    "RaisDastoor",
    "OnvanShobe",
    "EmzaEghdamgar",
    "EmzaRaisShobe",
    "EmzaJaneshin",
    "EmzaRais",
    "EmzaRaisDastoor",
    "AzTaraf",
    "NamoNeshan",
    "TarikhOdat",
    "EllateOdat",
    "OdatDahande",
    "Zamaem",
    "Shobe",
    "FareghOTahsiliDaraje",
    "FareghOTahsiliNoeEstekhdam",
    "FareghOTahsiliOnvaneTakhasos",
    "FareghOTahsiliShomareTakhasosJadid",
    "FareghOTahsiliShomareTakhasosGhadim",
    "FareghOTahsiliTarfiTarikh",
    "FareghOTahsiliTarikh",
    "FareghOTahsiliAghabOftadegi",
    "FareghOTahsiliMadrak",
    "FareghOTahsiliVaziatTaahol",
    "FareghOTahsiliYeganMontaghele",
  ],
  6: [
    "id",
    "Dastoor",
    "Madde",
    "Zirmadde",
    "ZirZirmadde",
    "Eghdamgar",
    "Girande1",
    "Girande2",
    "Girande3",
    "Girande4",
    "Girande5",
    "Girande6",
    "Girande7",
    "Girande8",
    "DastoorPeyravi",
    "MaddePeyravi",
    "SahebDastoorPeyravi",
    "DastoorPeyraviCheck",
    "DastoorPeyraviReport",
    "PerNo",
    "TarikhSabt",
    "Madrak",
    "TozihatTakmiliCheck",
    "TozihatTakmili",
    "GirandeCheck",
    "Girande2Check",
    "Girande3Check",
    "Girande4Check",
    "Girande5Check",
    "Girande6Check",
    "Girande7Check",
    "Girande8Check",
    "ToReport",
    "TozihatGozareshDastoor",
    "Date",
    "TaidEghdamgar",
    "TaidRaisShobe",
    "TaidJaneshin",
    "TaidRais",
    "TaidRaisDastoor",
    "EslahElat",
    "EslahTarikh",
    "ErteghaTarikh",
    "ErteghaMadde",
    "SeyrTedad",
    "GirandeLafz",
    "TarikhTaidRiasat",
    "TarikhTaidDastoor",
    "TarikhTaidRaisShobe",
    "RaisShobe",
    "Janeshin",
    "Rais",
    "RaisDastoor",
    "OnvanShobe",
    "EmzaEghdamgar",
    "EmzaRaisShobe",
    "EmzaJaneshin",
    "EmzaRais",
    "EmzaRaisDastoor",
    "AzTaraf",
    "NamoNeshan",
    "TarikhOdat",
    "EllateOdat",
    "OdatDahande",
    "Zamaem",
    "AmoozeshAwliPayan",
    "Shobe",
  ],
  7: [
    "id",
    "Dastoor",
    "Madde",
    "Zirmadde",
    "ZirZirmadde",
    "Eghdamgar",
    "Girande1",
    "Girande2",
    "Girande3",
    "Girande4",
    "DastoorPeyravi",
    "SahebDastoorPeyravi",
    "DastoorPeyraviCheck",
    "DastoorPeyraviReport",
    "PerNo",
    "TarikhSabt",
    "TarikhNahast",
    "TarikhFarar",
    "TarikhMorajeat",
    "Madrak",
    "TozihatTakmiliCheck",
    "TozihatTakmili",
    "GirandeCheck",
    "Girande2Check",
    "Girande3Check",
    "Girande4Check",
    "ToReport",
    "TozihatGozareshDastoor",
    "MorajeatNahast",
    "MorajeatFarar",
    "Date",
    "Girande5",
    "Girande6",
    "Girande7",
    "Girande8",
    "Girande5Check",
    "Girande6Check",
    "Girande7Check",
    "Girande8Check",
    "TaidEghdamgar",
    "TaidRaisShobe",
    "TaidJaneshin",
    "TaidRais",
    "TaidRaisDastoor",
    "GirandeLafz",
    "TarikhTaidRiasat",
    "TarikhTaidDastoor",
    "TarikhTaidRaisShobe",
    "RaisShobe",
    "Janeshin",
    "Rais",
    "RaisDastoor",
    "OnvanShobe",
    "EmzaEghdamgar",
    "EmzaRaisShobe",
    "EmzaJaneshin",
    "EmzaRais",
    "EmzaRaisDastoor",
    "AzTaraf",
    "NamoNeshan",
    "TarikhOdat",
    "EllateOdat",
    "OdatDahande",
    "Zamaem",
    "TaidJRaisShobe",
    "JRaisShobe",
    "TarikhTaidJRaisShobe",
    "EmzaJRaisShobe",
    "Shobe",
  ],
  9: [
    "id",
    "Dastoor",
    "Madde",
    "Zirmadde",
    "ZirZirmadde",
    "Eghdamgar",
    "Girande1",
    "Girande2",
    "Girande3",
    "Girande4",
    "Girande5",
    "Girande6",
    "Girande7",
    "Girande8",
    "DastoorPeyravi",
    "MaddePeyravi",
    "SahebDastoorPeyravi",
    "DastoorPeyraviCheck",
    "DastoorPeyraviReport",
    "PerNo",
    "TarikhSabt",
    "Madrak",
    "TozihatTakmiliCheck",
    "TozihatTakmili",
    "GirandeCheck",
    "Girande2Check",
    "Girande3Check",
    "Girande4Check",
    "Girande5Check",
    "Girande6Check",
    "Girande7Check",
    "Girande8Check",
    "ToReport",
    "TozihatGozareshDastoor",
    "Date",
    "TaidEghdamgar",
    "TaidRaisShobe",
    "TaidJaneshin",
    "TaidRais",
    "TaidRaisDastoor",
    "TakhlieEstenad",
    "TakhlieTarikh",
    "TakhlieMahal",
    "VagozariTarikh",
    "VagozariOnvan1",
    "VagozariOnvan2",
    "VagozariOnvan3",
    "VagozariOnvan4",
    "VagozariOnvan5",
    "VagozariHazine1",
    "VagozariHazine2",
    "VagozariHazine3",
    "VagozariHazine4",
    "VagozariHazine5",
    "GirandeLafz",
    "TarikhTaidRiasat",
    "TarikhTaidDastoor",
    "TarikhTaidRaisShobe",
    "RaisShobe",
    "Janeshin",
    "Rais",
    "RaisDastoor",
    "OnvanShobe",
    "EmzaEghdamgar",
    "EmzaRaisShobe",
    "EmzaJaneshin",
    "EmzaRais",
    "EmzaRaisDastoor",
    "AzTaraf",
    "NamoNeshan",
    "TarikhOdat",
    "EllateOdat",
    "OdatDahande",
    "Zamaem",
    "Shobe",
  ],
  10: [
    "id",
    "Dastoor",
    "Madde",
    "Zirmadde",
    "ZirZirmadde",
    "Eghdamgar",
    "Girande1",
    "Girande2",
    "Girande3",
    "Girande4",
    "DastoorPeyravi",
    "SahebDastoorPeyravi",
    "DastoorPeyraviCheck",
    "DastoorPeyraviReport",
    "PerNo",
    "TarikhSabt",
    "Madrak",
    "TozihatTakmiliCheck",
    "TozihatTakmili",
    "GirandeCheck",
    "Girande2Check",
    "Girande3Check",
    "Girande4Check",
    "ToReport",
    "TozihatGozareshDastoor",
    "TarikhErtegha",
    "DalileErtegha",
    "NoeErtegha",
    "NoePaziresh",
    "PazireshMaghta",
    "PazireshReshte",
    "PazireshTarikhFaregh",
    "PazireshMahalTahsil",
    "PazireshTarikhPaziresh",
    "PazireshTakhasosFeli",
    "ErteghaTakhasos",
    "ModatSanavat",
    "NoeKhedmat",
    "TarikhShoru",
    "TarikhPayan",
    "YeganTaeed",
    "EstenadieSanavat",
    "TakhasosGhabli",
    "TakhasosJadid",
    "TarikhTaghirTakhasos",
    "TakhasosEstenadie",
    "GoruhGhadim",
    "GoruhJadid",
    "RadeGhadim",
    "RadeJadid",
    "Date",
    "Girande5",
    "Girande6",
    "Girande7",
    "Girande8",
    "Girande5Check",
    "Girande6Check",
    "Girande7Check",
    "Girande8Check",
    "TaidEghdamgar",
    "TaidRaisShobe",
    "TaidJaneshin",
    "TaidRais",
    "TaidRaisDastoor",
    "GirandeLafz",
    "TarikhTaidRiasat",
    "TarikhTaidDastoor",
    "TarikhTaidRaisShobe",
    "RaisShobe",
    "Janeshin",
    "Rais",
    "RaisDastoor",
    "OnvanShobe",
    "EmzaEghdamgar",
    "EmzaRaisShobe",
    "EmzaJaneshin",
    "EmzaRais",
    "EmzaRaisDastoor",
    "AzTaraf",
    "NamoNeshan",
    "TarikhOdat",
    "EllateOdat",
    "OdatDahande",
    "Zamaem",
    "TaidJRaisShobe",
    "JRaisShobe",
    "TarikhTaidJRaisShobe",
    "EmzaJRaisShobe",
    "ArshadiatMadrak",
    "ArshadiatModat",
    "ArshadiatJamKol",
    "ArshadiatTarikh",
    "TarikhBargharari",
    "Shobe",
  ],
  11: [
    "id",
    "Dastoor",
    "Madde",
    "Zirmadde",
    "ZirZirmadde",
    "Eghdamgar",
    "Girande1",
    "Girande2",
    "Girande3",
    "Girande4",
    "DastoorPeyravi",
    "SahebDastoorPeyravi",
    "DastoorPeyraviCheck",
    "DastoorPeyraviReport",
    "PerNo",
    "TarikhSabt",
    "Madrak",
    "TozihatTakmiliCheck",
    "TozihatTakmili",
    "GirandeCheck",
    "Girande2Check",
    "Girande3Check",
    "Girande4Check",
    "ToReport",
    "Nesbat",
    "NamoNesh",
    "CodeMelli",
    "ShomareShenasname",
    "SerialShenasname",
    "TarikhTavalod",
    "MahalTavalod",
    "NamPedar",
    "Shoghl",
    "ShomareBimeh",
    "MoshakhasatTaghiri",
    "MoshakhasatGhadimi",
    "MoshakhasatJadid",
    "MaghtaTahsili",
    "Reshte",
    "Daneshgah",
    "MohlatEstefade",
    "TarikhEzdevaj",
    "CheckEzdevajDovom",
    "ShomarFarzand",
    "ShomarJensiat",
    "TarikhKhorujAzAele",
    "TarikhVafat",
    "TarikhEzdevajFarzand",
    "TozihatGozareshDastoor",
    "Date",
    "Girande5",
    "Girande6",
    "Girande7",
    "Girande8",
    "Girande5Check",
    "Girande6Check",
    "Girande7Check",
    "Girande8Check",
    "TaidEghdamgar",
    "TaidRaisShobe",
    "TaidJaneshin",
    "TaidRais",
    "TaidRaisDastoor",
    "GirandeLafz",
    "TarikhTaidRiasat",
    "TarikhTaidDastoor",
    "TarikhTaidRaisShobe",
    "RaisShobe",
    "Janeshin",
    "Rais",
    "RaisDastoor",
    "OnvanShobe",
    "EmzaEghdamgar",
    "EmzaRaisShobe",
    "EmzaJaneshin",
    "EmzaRais",
    "EmzaRaisDastoor",
    "AzTaraf",
    "NamoNeshan",
    "TarikhOdat",
    "EllateOdat",
    "OdatDahande",
    "Zamaem",
    "TaidJRaisShobe",
    "JRaisShobe",
    "TarikhTaidJRaisShobe",
    "EmzaJRaisShobe",
    "Shobe",
  ],
  12: [
    "id",
    "Dastoor",
    "Madde",
    "Zirmadde",
    "ZirZirmadde",
    "Eghdamgar",
    "Girande1",
    "Girande2",
    "Girande3",
    "Girande4",
    "DastoorPeyravi",
    "SahebDastoorPeyravi",
    "DastoorPeyraviCheck",
    "DastoorPeyraviReport",
    "PerNo",
    "TarikhSabt",
    "Madrak",
    "TozihatTakmiliCheck",
    "TozihatTakmili",
    "GirandeCheck",
    "Girande2Check",
    "Girande3Check",
    "Girande4Check",
    "ToReport",
    "TozihatGozareshDastoor",
    "Date",
    "TarikhNahast",
    "ModatNahast",
    "Estenadie",
    "NoeTanbih",
    "ElateTanbih",
    "CodeTanbihat",
    "EstenadieTanbih",
    "NoeTanbihTanbih",
    "TarikhTanbih",
    "TarikhFarar",
    "Morajeat",
    "Jarime",
    "Jaza",
    "TakhfifJaza",
    "NoeTanbihKan",
    "EllateTanbihatKan",
    "TarikhTanbihKan",
    "TanzilEllat",
    "TanzilTarikh",
    "TanzilNoeTanbih",
    "KhorujBedunTarikhSH",
    "KhorujBedunTarikhPa",
    "BedunKarEllat",
    "BedunKarNoe",
    "BednKarTarikhSh",
    "BedunKarTarikhPa",
    "TarikhMahkum",
    "Girande5",
    "Girande6",
    "Girande7",
    "Girande8",
    "Girande5Check",
    "Girande6Check",
    "Girande7Check",
    "Girande8Check",
    "TaidEghdamgar",
    "TaidRaisShobe",
    "TaidJaneshin",
    "TaidRais",
    "TaidRaisDastoor",
    "GirandeLafz",
    "TarikhTaidRiasat",
    "TarikhTaidDastoor",
    "TarikhTaidRaisShobe",
    "RaisShobe",
    "Janeshin",
    "Rais",
    "RaisDastoor",
    "OnvanShobe",
    "EmzaEghdamgar",
    "EmzaRaisShobe",
    "EmzaJaneshin",
    "EmzaRais",
    "EmzaRaisDastoor",
    "AzTaraf",
    "NamoNeshan",
    "TarikhOdat",
    "EllateOdat",
    "OdatDahande",
    "Zamaem",
    "TanbihNahast",
    "ModatTanbihNahast",
    "TaTarikhNahast",
    "TaidJRaisShobe",
    "JRaisShobe",
    "TarikhTaidJRaisShobe",
    "EmzaJRaisShobe",
    "noeeBkari",
    "elatBkari",
    "Shobe",
  ],
  15: [
    "id",
    "Dastoor",
    "Madde",
    "Zirmadde",
    "ZirZirmadde",
    "Eghdamgar",
    "Girande1",
    "Girande2",
    "Girande3",
    "Girande4",
    "DastoorPeyravi",
    "SahebDastoorPeyravi",
    "DastoorPeyraviCheck",
    "DastoorPeyraviReport",
    "PerNo",
    "Tarikh",
    "TarikhSabt",
    "Madrak",
    "TozihatTakmiliCheck",
    "TozihatTakmili",
    "GirandeCheck",
    "Girande2Check",
    "Girande3Check",
    "Girande4Check",
    "ToReport",
    "TabagheBimari1",
    "TabagheTarikh",
    "TabagheShenase1",
    "Tabaghe1",
    "TabagheModat1",
    "TabagheDovomCheck",
    "TabagheBimari2",
    "TabagheShenase2",
    "Tabaghe2",
    "tabagheModat2",
    "EsterahatTarikh",
    "EsterahatModat",
    "SabSurat",
    "SabBimari",
    "SabTarikh",
    "JanSurat",
    "JanDarsad",
    "JanModat",
    "AshaeTakhasos",
    "AshaeSemat",
    "AshaeTarikh",
    "AshaeEstenadie",
    "AshaeAsas",
    "AshaeGoruhParto",
    "AshaeModat",
    "AmelSemat",
    "AmelYegan",
    "AmelDore",
    "TozihatGozareshDastoor",
    "Date",
    "Girande5",
    "Girande6",
    "Girande7",
    "Girande8",
    "Girande5Check",
    "Girande6Check",
    "Girande7Check",
    "Girande8Check",
    "TaidEghdamgar",
    "TaidRaisShobe",
    "TaidJaneshin",
    "TaidRais",
    "TaidRaisDastoor",
    "GirandeLafz",
    "TarikhTaidRiasat",
    "TarikhTaidDastoor",
    "TarikhTaidRaisShobe",
    "RaisShobe",
    "Janeshin",
    "Rais",
    "RaisDastoor",
    "OnvanShobe",
    "EmzaEghdamgar",
    "EmzaRaisShobe",
    "EmzaJaneshin",
    "EmzaRais",
    "EmzaRaisDastoor",
    "AzTaraf",
    "NamoNeshan",
    "TarikhOdat",
    "EllateOdat",
    "OdatDahande",
    "Zamaem",
    "TaidJRaisShobe",
    "JRaisShobe",
    "TarikhTaidJRaisShobe",
    "EmzaJRaisShobe",
    "tozihattabaghe1",
    "tozihattabaghe2",
    "Shobe",
  ],
};
